<aside class="max-sm:w-0 max-sm:px-0 w-20 bg-[linear-gradient(to_bottom,_#6a11cb,_#a044ff)] text-white pt-3 pb-4  flex flex-col gap-4 [transition:width_0.3s_ease] overflow-auto sm:hover:w-72 sm:hover:items-start group">
    <nav class="flex flex-col w-full overflow-auto">
        <div class="text-white no-underline flex items-center whitespace-nowrap overflow-hidden [transition:background_0.3s] rounded-md pt-3 pb-2 font-bold text-xl leading-[1.2]">
            <img class="ml-4 mr-2 w-12 h-auto max-w-none" src="assets/core/TomYang-Logo.png" alt="Logo"><span name="sidebar-text" class="opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">TOM YANG<br>UNIVERSITY</span>
        </div>
        <div class="mt-3 overflow-y-auto overflow-x-hidden">
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Dashboard-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Applicant Dashboard</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Criteria-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Admission Criteria</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Applications-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Application Form</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Documents-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Document Requirements</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/InterviewScheduling-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Interview Schedule</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/TestScheduling-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Admission Test</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/AdmissionResult-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Admission Result</span></a>
            <a class="mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/FAQ-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">FAQs</span></a>
            <a class="sm:hidden mb-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Phone-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Feedback & Survey</span></a>
        </div>
    </nav>
    <nav class="flex flex-col w-full mt-auto overflow-x-hidden">
        <a class="sm:hidden mt-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 mr-0 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Notification-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">Notifications</span></a>
        <a class="sm:hidden mt-2 ml-4 mr-6 text-white no-underline flex items-center font-medium whitespace-nowrap overflow-hidden p-3 [transition:background_0.3s] rounded-md hover:bg-[rgba(0,_0,_0,_0.3)]" href="#"><img class="w-5 mr-0 [transition:margin_0.3s_ease] sm:group-hover:mr-3 max-w-none" src="assets/core/Profile-Icon.png"><span name="sidebar-text" class="text-base opacity-0 [transition:opacity_0.3s_ease,_margin-left_0.3s_ease] ml-0 sm:group-hover:opacity-100 sm:group-hover:ml-1">My Profile</span></a>
    </nav>
</aside>